// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package snowflakesso.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IUser;
import com.mendix.systemwideinterfaces.core.UserAction;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class GetCompoundToken extends UserAction<java.lang.String>
{
	public GetCompoundToken(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = getContext();
		IContext systemContext = Core.createSystemContext();

		// Read the service OAuth token (auto-refreshed by SPCS)
		Path tokenPath = Paths.get("/snowflake/session/token");
		if (!Files.exists(tokenPath)) {
			throw new RuntimeException(
				"Service token not found at /snowflake/session/token. "
				+ "This action can only run inside an SPCS container.");
		}
		String serviceToken = new String(Files.readAllBytes(tokenPath)).trim();

		// Get the caller token from the current user's SnowflakeUser entity
		IUser currentUser = context.getSession().getUser(context);
		if (currentUser == null) {
			throw new RuntimeException("No authenticated user in the current session.");
		}

		IMendixObject userObj = currentUser.getMendixObject();
		if (!userObj.isInstanceOf(snowflakesso.proxies.SnowflakeUser.getType())) {
			throw new RuntimeException(
				"User " + currentUser.getName() + " is not a SnowflakeUser. "
				+ "Log out and log back in via the Snowflake SSO handler.");
		}

		snowflakesso.proxies.SnowflakeUser sfUser =
			snowflakesso.proxies.SnowflakeUser.initialize(systemContext, userObj);
		String callerToken = sfUser.getCallerToken(systemContext);

		if (callerToken == null || callerToken.isBlank()) {
			throw new RuntimeException(
				"No caller token stored for user: " + currentUser.getName()
				+ ". Ensure executeAsCaller is enabled on the service spec "
				+ "and the user logged in via the Snowflake SSO handler.");
		}

		// Compound token format: serviceToken.callerToken
		return serviceToken + "." + callerToken;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetCompoundToken";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
