// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
let refreshInterval = null;
// END EXTRA CODE

/**
 * @returns {Promise.<boolean>}
 */
export async function RefreshCallerToken() {
	// BEGIN USER CODE
	const doRefresh = async () => {
		try {
			const response = await fetch("/headersso/refresh", {
				method: "GET",
				credentials: "same-origin"
			});
			return response.status === 204;
		} catch (e) {
			console.warn("SnowflakeSSO: token refresh failed", e);
			return false;
		}
	};

	// Schedule recurring refresh every 20 minutes (only one interval active)
	if (refreshInterval === null) {
		refreshInterval = setInterval(doRefresh, 20 * 60 * 1000);
	}

	// Execute immediately on first call
	return await doRefresh();
	// END USER CODE
}
