// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
let refreshInterval = null;
let visibilityListenerAttached = false;
let lastRefreshAtMillis = 0;
const REFRESH_INTERVAL_MILLIS = 20 * 60 * 1000;
// Suppress a visibility-triggered refresh if one just happened - avoids a burst
// of redundant calls from rapid tab-switching or duplicate visibilitychange events.
const MIN_MILLIS_BETWEEN_REFRESHES = 60 * 1000;
// END EXTRA CODE

/**
 * @returns {Promise.<boolean>}
 */
export async function RefreshCallerToken() {
	// BEGIN USER CODE
	const doRefresh = async () => {
		lastRefreshAtMillis = Date.now();
		try {
			const response = await fetch("/headersso/refresh", {
				method: "GET",
				credentials: "same-origin"
			});
			return response.status === 204;
		} catch (e) {
			console.warn("SnowflakeSSO: token refresh failed", e);
			return false;
		}
	};

	// Schedule recurring refresh every 20 minutes (only one interval active)
	if (refreshInterval === null) {
		refreshInterval = setInterval(doRefresh, REFRESH_INTERVAL_MILLIS);
	}

	// The fixed interval above stops firing reliably once the tab is backgrounded
	// (browsers throttle timers in inactive tabs), so a user who tabs away for
	// longer than the server-side cache's TTL and comes back would otherwise find
	// their caller token already evicted. Catch that up by refreshing immediately
	// whenever the tab becomes visible again, not just waiting for the next tick.
	if (!visibilityListenerAttached) {
		visibilityListenerAttached = true;
		document.addEventListener("visibilitychange", () => {
			if (document.visibilityState !== "visible") {
				return;
			}
			if (Date.now() - lastRefreshAtMillis < MIN_MILLIS_BETWEEN_REFRESHES) {
				return;
			}
			doRefresh();
		});
	}

	// Execute immediately on first call
	return await doRefresh();
	// END USER CODE
}
