# Update-SnowflakeSSOMpk.ps1 - Repackage SnowflakeSSO.mpk from the tracked Source folder,
# without going through Mendix Studio Pro.
#
# Source/ mirrors the .mpk's own zip layout 1:1 (javasource/<module>/actions/*.java,
# javascriptsource/<module>/actions/*.js, themesource/<module>/**), so a repo-relative
# path under Source/ IS the zip entry path.
#
# Why this is safe: a .mpk is a zip of project.mpr (a SQLite DB holding the module's model -
# domain model, and each Java/JS action's declared name/parameters/return type) plus the
# action bodies and theme assets as plain files. Editing the body of an EXISTING action is
# just a text-file change; project.mpr doesn't need to change for that. This script extracts
# the current .mpk, overlays the files below from Source/, and re-zips - project.mpr and any
# file not listed in $files are left byte-for-byte untouched.
#
# This does NOT cover: adding/removing an action, changing an action's parameters or return
# type, or any domain model / microflow change. Those are real changes to project.mpr and
# still require Studio Pro.
#
# Usage:
#   .\Update-SnowflakeSSOMpk.ps1            # repackage if Source/ differs from the .mpk
#   .\Update-SnowflakeSSOMpk.ps1 -WhatIf    # show what would change, write nothing

param(
    [switch]$WhatIf
)

$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$moduleDir = Split-Path -Parent $scriptDir
$sourceDir = Join-Path $moduleDir "Source"
$mpkPath   = Join-Path $moduleDir "SnowflakeSSO.mpk"

if (-not (Test-Path $mpkPath)) {
    Write-Error "Not found: $mpkPath"
}

# Paths under Source/, identical to their entry path inside the .mpk.
# themesource/ is deliberately excluded: it's autogenerated boilerplate, not maintained here.
$files = @(
    "javasource/snowflakesso/actions/HeaderSSOHandler.java"
    "javasource/snowflakesso/actions/RegisterHeaderSSO.java"
    "javasource/snowflakesso/actions/GetCompoundToken.java"
    "javascriptsource/snowflakesso/actions/RefreshCallerToken.js"
)

Add-Type -AssemblyName System.IO.Compression.FileSystem

$tmpDir = Join-Path $env:TEMP ("SnowflakeSSO_mpk_" + [guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Path $tmpDir | Out-Null

try {
    [System.IO.Compression.ZipFile]::ExtractToDirectory($mpkPath, $tmpDir)

    # Sanity check: warn if the .mpk now contains a Java/JS action this script doesn't know
    # about (usually means an action was added in Studio Pro since $files was written).
    # themesource/ is intentionally unmanaged - not checked here.
    $packageXmlPath = Join-Path $tmpDir "package.xml"
    if (Test-Path $packageXmlPath) {
        [xml]$packageXml = Get-Content $packageXmlPath -Raw
        foreach ($file in $packageXml.package.modelerProject.files.file) {
            $p = $file.path
            if ($p -notlike "javasource/*" -and $p -notlike "javascriptsource/*") { continue }
            if ($files -notcontains $p) {
                Write-Warning "package.xml lists '$p' which isn't in `$files - add it so it stays in sync with Source/."
            }
        }
    }

    $changed = @()
    foreach ($relPath in $files) {
        $srcPath = Join-Path $sourceDir ($relPath -replace "/", "\")
        if (-not (Test-Path $srcPath)) {
            Write-Warning "Missing repo source file, skipping: $srcPath"
            continue
        }

        $dstPath = Join-Path $tmpDir ($relPath -replace "/", "\")
        $dstDir = Split-Path -Parent $dstPath
        if (-not (Test-Path $dstDir)) { New-Item -ItemType Directory -Path $dstDir -Force | Out-Null }

        $srcBytes = [System.IO.File]::ReadAllBytes($srcPath)
        $isNewOrChanged = $true
        if (Test-Path $dstPath) {
            $existingBytes = [System.IO.File]::ReadAllBytes($dstPath)
            $isNewOrChanged = -not [System.Linq.Enumerable]::SequenceEqual($srcBytes, $existingBytes)
        }

        if ($isNewOrChanged) {
            Copy-Item -Path $srcPath -Destination $dstPath -Force
            $changed += $relPath
        }
    }

    if ($changed.Count -eq 0) {
        Write-Host "No source changes detected; $mpkPath is already up to date." -ForegroundColor Green
        return
    }

    Write-Host "Files changed since last package:" -ForegroundColor Cyan
    $changed | ForEach-Object { Write-Host "  $_" }

    if ($WhatIf) {
        Write-Host "-WhatIf specified; $mpkPath was not modified." -ForegroundColor Yellow
        return
    }

    $backupPath = "$mpkPath.bak"
    Copy-Item -Path $mpkPath -Destination $backupPath -Force
    Write-Host "Backed up previous package to $backupPath"

    Remove-Item $mpkPath -Force

    $zip = [System.IO.Compression.ZipFile]::Open($mpkPath, [System.IO.Compression.ZipArchiveMode]::Create)
    try {
        Get-ChildItem -Path $tmpDir -Recurse -File | ForEach-Object {
            $relative = $_.FullName.Substring($tmpDir.Length + 1) -replace "\\", "/"
            [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile(
                $zip, $_.FullName, $relative, [System.IO.Compression.CompressionLevel]::Optimal
            ) | Out-Null
        }
    } finally {
        $zip.Dispose()
    }

    Write-Host "Repackaged $mpkPath" -ForegroundColor Green
}
finally {
    Remove-Item -Path $tmpDir -Recurse -Force -ErrorAction SilentlyContinue
}
